/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIdRouteImport } from './routes/pacientes.$id'

const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pacientes/$id': typeof PacientesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/configuracoes' | '/login' | '/pacientes' | '/pacientes/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/configuracoes' | '/login' | '/pacientes' | '/pacientes/$id'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/login'
    | '/pacientes'
    | '/pacientes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof PacientesRoute
    }
  }
}

interface PacientesRouteChildren {
  PacientesIdRoute: typeof PacientesIdRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesIdRoute: PacientesIdRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
