/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PacientesIdRouteImport } from './routes/pacientes.$id'
import { Route as ApiPublicExtensionGenerateRouteImport } from './routes/api/public/extension/generate'
import { Route as ApiPublicExtensionConfirmRouteImport } from './routes/api/public/extension/confirm'
import { Route as ApiPublicExtensionChatGenerateRouteImport } from './routes/api/public/extension/chat-generate'

const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesIdRoute = PacientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PacientesRoute,
} as any)
const ApiPublicExtensionGenerateRoute =
  ApiPublicExtensionGenerateRouteImport.update({
    id: '/api/public/extension/generate',
    path: '/api/public/extension/generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionConfirmRoute =
  ApiPublicExtensionConfirmRouteImport.update({
    id: '/api/public/extension/confirm',
    path: '/api/public/extension/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionChatGenerateRoute =
  ApiPublicExtensionChatGenerateRouteImport.update({
    id: '/api/public/extension/chat-generate',
    path: '/api/public/extension/chat-generate',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pacientes/$id': typeof PacientesIdRoute
  '/api/public/extension/chat-generate': typeof ApiPublicExtensionChatGenerateRoute
  '/api/public/extension/confirm': typeof ApiPublicExtensionConfirmRoute
  '/api/public/extension/generate': typeof ApiPublicExtensionGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pacientes/$id': typeof PacientesIdRoute
  '/api/public/extension/chat-generate': typeof ApiPublicExtensionChatGenerateRoute
  '/api/public/extension/confirm': typeof ApiPublicExtensionConfirmRoute
  '/api/public/extension/generate': typeof ApiPublicExtensionGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/pacientes/$id': typeof PacientesIdRoute
  '/api/public/extension/chat-generate': typeof ApiPublicExtensionChatGenerateRoute
  '/api/public/extension/confirm': typeof ApiPublicExtensionConfirmRoute
  '/api/public/extension/generate': typeof ApiPublicExtensionGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/login'
    | '/pacientes'
    | '/pacientes/$id'
    | '/api/public/extension/chat-generate'
    | '/api/public/extension/confirm'
    | '/api/public/extension/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/login'
    | '/pacientes'
    | '/pacientes/$id'
    | '/api/public/extension/chat-generate'
    | '/api/public/extension/confirm'
    | '/api/public/extension/generate'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/login'
    | '/pacientes'
    | '/pacientes/$id'
    | '/api/public/extension/chat-generate'
    | '/api/public/extension/confirm'
    | '/api/public/extension/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  LoginRoute: typeof LoginRoute
  PacientesRoute: typeof PacientesRouteWithChildren
  ApiPublicExtensionChatGenerateRoute: typeof ApiPublicExtensionChatGenerateRoute
  ApiPublicExtensionConfirmRoute: typeof ApiPublicExtensionConfirmRoute
  ApiPublicExtensionGenerateRoute: typeof ApiPublicExtensionGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$id': {
      id: '/pacientes/$id'
      path: '/$id'
      fullPath: '/pacientes/$id'
      preLoaderRoute: typeof PacientesIdRouteImport
      parentRoute: typeof PacientesRoute
    }
    '/api/public/extension/generate': {
      id: '/api/public/extension/generate'
      path: '/api/public/extension/generate'
      fullPath: '/api/public/extension/generate'
      preLoaderRoute: typeof ApiPublicExtensionGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/confirm': {
      id: '/api/public/extension/confirm'
      path: '/api/public/extension/confirm'
      fullPath: '/api/public/extension/confirm'
      preLoaderRoute: typeof ApiPublicExtensionConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/chat-generate': {
      id: '/api/public/extension/chat-generate'
      path: '/api/public/extension/chat-generate'
      fullPath: '/api/public/extension/chat-generate'
      preLoaderRoute: typeof ApiPublicExtensionChatGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PacientesRouteChildren {
  PacientesIdRoute: typeof PacientesIdRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesIdRoute: PacientesIdRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  LoginRoute: LoginRoute,
  PacientesRoute: PacientesRouteWithChildren,
  ApiPublicExtensionChatGenerateRoute: ApiPublicExtensionChatGenerateRoute,
  ApiPublicExtensionConfirmRoute: ApiPublicExtensionConfirmRoute,
  ApiPublicExtensionGenerateRoute: ApiPublicExtensionGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
